name = "BreakUnfold"
uuid = "27c6bf10-064e-4fe1-bfd2-d9d2a3e8113f"
authors = ["Ren√© Skukies"]

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SwarmMakie = "0b1c068e-6a84-4e66-8136-5c95cafa83ed"
Unfold = "181c99d8-e21b-4ff3-b70b-c233eddec679"
UnfoldSim = "ed8ae6d2-84d3-44c6-ab46-0baf21700804"

[compat]
GlobalSensitivity = "2.8.0"
LinearAlgebra = "1.11.0"
LoggingExtras = "1.1.0"
Parameters = "0.12.3"
QuasiMonteCarlo = "0.3.3"
StatsBase = "0.34.4"
